pipelines:
  - name: example-app
    phases:
      ci:
        source:
          kind: ci
          name: get-glu/example-app
        config:
          scm: github
          repository: get-glu/example-app
      
      oci:
        source:
          kind: oci
          name: app
        depends_on: ci
      
      staging:
        source:
          kind: kubernetes
          name: staging
        depends_on: oci
        labels:
          url: http://0.0.0.0:30081
        config:
          namespace: default
          name: example
          container: exampled
      
      production:
        source:
          kind: kubernetes
          name: production
        depends_on: staging
        labels:
          url: http://0.0.0.0:30082
        config:
          namespace: production
          name: example-app
          container: example-app
