// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("github")
	ScopeName = "github.com/get-glu/glu/otel/receiver/githubreceiver"
)

const (
	TracesStability = component.StabilityLevelAlpha
)
