// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("k8s")
	ScopeName = "github.com/get-glu/glu/otel/receiver/k8sreceiver"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
